version: "3.11"

services:

  fastapi:
    build: .
    container_name: aka_taxi_project
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - media_volume:/uploads
    env_file:
      - ../AKA_Taxi_maxsus_texnika/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: aka_taxi_database
    image: postgres:15.0-alpine
    env_file:
      - ../AKA_Taxi_maxsus_texnika/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}


volumes:
  media_volume:

